
# checkpoint: "/media/D3/tester/reresearch/_plt/propertest/finetune/test.ckpt"
checkpoint: 
  - "./checkpoint/finetune/base_dedup1/classifier.ckpt"

device: "cuda:3"
data_dir: "./data/dedup/test"

pl_cls_version: 2

schema:
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "data"
      - _target_: src.util.dynamic_load
        item: torch.float
      - _target_: src.util.dynamic_load
        item: src.util.staged_mu_law
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "label"
      - _target_: src.util.dynamic_load
        item: torch.long
      - _target_: src.util.dynamic_load
        item: src.util.minus_one

batch_size: 32
num_workers: 4
n_class: 6

metrics:
  - balanced_accuracy
  - cohen_kappa
  - f1_weighted