postfix: iccc_all_test_b512ga_cross
# checkpoint: "/media/D3/tester/reresearch/_plt/propertest/finetune/test.ckpt"
checkpoint: 
  - "./checkpoint/finetune/base_${report.postfix}/classifier.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v1.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v2.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v3.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v4.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v5.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v6.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v7.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v8.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v9.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v10.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v11.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v12.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v13.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v14.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v15.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v16.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v17.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v18.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v19.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v20.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v21.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v22.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v23.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v24.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v25.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v26.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v27.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v28.ckpt"
  - "./checkpoint/finetune/base_${report.postfix}/classifier-v29.ckpt"

device: "cuda:6"
data_dir: "./data/iiic/all/test"

pl_cls_version: 2

schema:
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "signal"
      - _target_: src.util.dynamic_load
        item: torch.float
      - _target_: src.util.dynamic_load
        item: src.util.staged_mu_law
  - _target_: dataloader.TUEVDataset.TUEVDataField
    _args_:
      - "label"
      - _target_: src.util.dynamic_load
        item: torch.long

batch_size: 24
num_workers: 4
n_class: 6

metrics:
  - balanced_accuracy
  - cohen_kappa
  - f1_weighted